apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.app.name}}-configmap
  namespace: {{.Values.app.name}}-namespace-{{.Values.app.release}}
data:
  {{- range $key, $value := .Values.app.environment}}
  {{ $key }}: {{ toYaml $value }}
  {{- end }}
