apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: ibconnect-dci
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      name: echo-server
      labels:
        app: echo-server
    spec:
      containers:
      - image: jmalloc/echo-server
        name: echo-server
