apiVersion: v1
kind: Namespace
metadata:
  name: postgres-namespace-dev
  annotations:
    field.cattle.io/projectId: "c-j454z:p-6h468"
  labels:
    field.cattle.io/projectId: c-j454z
    name: postgres
