apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.app.name}}-namespace-{{.Values.app.release}}
  annotations:
    field.cattle.io/projectId: "{{.Values.rancher.clusterId}}:{{.Values.rancher.projectId}}"
  labels:
    field.cattle.io/projectId: {{.Values.rancher.projectId}}
    name: {{.Values.app.name}}
