apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    cattle.io/creator: norman
  name: echo-server-service
  namespace: ibconnect-dci
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: echo-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
