apiVersion: v1
kind: Service
metadata:
  name: postgres-service-lb
  namespace: postgres-namespace-dev
spec:
  ports:
  - name: psql-lb
    port: 8080
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-deployment-dev
  type: LoadBalancer
