apiVersion: v1
kind: Service
metadata:
  name: postgres-service-nport
  namespace: postgres-namespace-dev
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: psql-port
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-deployment-dev
  type: NodePort
