apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-volume-dev
  namespace: postgres-namespace-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
